### ISSUE TITLE
Game crashes on boot from this mod

### ISSUE THREAD

**Issue by royalcw** [GoryMoon/ViesCraftTweaker#3]
Minecraft Version: 1.12.2
Forge: 14.23.4.2705
Viescraft Version: 5.9.13
ViesCraft Tweaker: 2.3.10

Issue:  Game crashes during boot.  Remove ViesCraft Tweaker and the game boots up with no issues.  The game worked with this move for Forge Version 14.23.3.2675 but any newer forge versions crash with this mod installed.  

Crash Report doesn't specifically say ViesCraft Tweaker but I painstakingly eliminated one mod at a time until this one was isolated then added back in my other mods.

---- Minecraft Crash Report ----

WARNING: coremods are present:
  VCTweakerCore (ViesCraftTweaker-1.12.2-2.3.10.jar)
Contact their authors BEFORE contacting forge

// Ooh. Shiny.

Time: 5/31/18 10:13 PM
Description: Initializing game

java.lang.NullPointerException: Initializing game
	at net.minecraftforge.fml.common.versioning.ComparableVersion.compareTo(ComparableVersion.java:468)
	at net.minecraftforge.fml.common.versioning.DefaultArtifactVersion.compareTo(DefaultArtifactVersion.java:61)
	at net.minecraftforge.fml.common.versioning.DefaultArtifactVersion.compareTo(DefaultArtifactVersion.java:22)
	at net.minecraftforge.fml.common.versioning.Restriction.containsVersion(Restriction.java:78)
	at net.minecraftforge.fml.common.versioning.VersionRange.containsVersion(VersionRange.java:529)
	at net.minecraftforge.fml.common.versioning.DefaultArtifactVersion.containsVersion(DefaultArtifactVersion.java:83)
	at net.minecraftforge.fml.common.versioning.DefaultArtifactVersion.equals(DefaultArtifactVersion.java:55)
	at java.util.Collections.eq(Collections.java:5250)
	at java.util.Collections$SingletonSet.contains(Collections.java:4762)
	at net.minecraftforge.fml.common.Loader.sortModList(Loader.java:267)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:570)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:225)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraftforge.fml.common.versioning.ComparableVersion.compareTo(ComparableVersion.java:468)
	at net.minecraftforge.fml.common.versioning.DefaultArtifactVersion.compareTo(DefaultArtifactVersion.java:61)
	at net.minecraftforge.fml.common.versioning.DefaultArtifactVersion.compareTo(DefaultArtifactVersion.java:22)
	at net.minecraftforge.fml.common.versioning.Restriction.containsVersion(Restriction.java:78)
	at net.minecraftforge.fml.common.versioning.VersionRange.containsVersion(VersionRange.java:529)
	at net.minecraftforge.fml.common.versioning.DefaultArtifactVersion.containsVersion(DefaultArtifactVersion.java:83)
	at net.minecraftforge.fml.common.versioning.DefaultArtifactVersion.equals(DefaultArtifactVersion.java:55)
	at java.util.Collections.eq(Collections.java:5250)
	at java.util.Collections$SingletonSet.contains(Collections.java:4762)
	at net.minecraftforge.fml.common.Loader.sortModList(Loader.java:267)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:570)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:225)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 882610872 bytes (841 MB) / 1084227584 bytes (1034 MB) up to 5726797824 bytes (5461 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx6144m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.4.2705 28 mods loaded, 28 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                 | Version          | Source                                          | Signature                                |
	|:----- |:------------------ |:---------------- |:----------------------------------------------- |:---------------------------------------- |
	| U     | minecraft          | 1.12.2           | minecraft.jar                                   | None                                     |
	| U     | mcp                | 9.42             | minecraft.jar                                   | None                                     |
	| U     | FML                | 8.0.99.99        | forge-1.12.2-14.23.4.2705.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| U     | forge              | 14.23.4.2705     | forge-1.12.2-14.23.4.2705.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| U     | vctweaker          | 2.3              | ViesCraftTweaker-1.12.2-2.3.10.jar              | f2ae887a76e1b521b51bb44cf136918015b5927a |
	| U     | baubles            | 1.5.2            | Baubles-1.12-1.5.2.jar                          | None                                     |
	| U     | codechickenlib     | 3.1.8.341        | CodeChickenLib-1.12.2-3.1.8.341-universal.jar   | None                                     |
	| U     | cofhcore           | 4.5.1            | CoFHCore-1.12.2-4.5.1.18-universal.jar          | None                                     |
	| U     | cofhworld          | 1.2.0            | CoFHWorld-1.12.2-1.2.0.5-universal.jar          | None                                     |
	| U     | ctgui              | 1.0.0            | CraftTweaker2-1.12-4.1.8.jar                    | None                                     |
	| U     | crafttweaker       | 4.1.8            | CraftTweaker2-1.12-4.1.8.jar                    | None                                     |
	| U     | crafttweakerjei    | 2.0.2            | CraftTweaker2-1.12-4.1.8.jar                    | None                                     |
	| U     | forestry           | 5.8.0.295        | forestry_1.12.2-5.8.0.295.jar                   | None                                     |
	| U     | jei                | 4.9.2.196        | jei_1.12.2-4.9.2.196.jar                        | None                                     |
	| U     | jeibees            | 0.9.0.5          | jeibees-0.9.0.5-mc1.12.2.jar                    | None                                     |
	| U     | mantle             | 1.12-1.3.2.24    | Mantle-1.12-1.3.2.24.jar                        | None                                     |
	| U     | redstonearsenal    | 2.5.0            | RedstoneArsenal-1.12.2-2.5.0.10-universal.jar   | None                                     |
	| U     | redstoneflux       | 2.0.2            | RedstoneFlux-1.12-2.0.2.3-universal.jar         | None                                     |
	| U     | tconstruct         | 1.12.2-2.10.0.81 | TConstruct-1.12.2-2.10.0.81.jar                 | None                                     |
	| U     | thaumcraft         | 6.1.BETA15       | Thaumcraft-1.12.2-6.1.BETA15.jar                | None                                     |
	| U     | thaumicjei         | 1.2.1            | ThaumicJEI-1.12.2-1.3.0-11.jar                  | None                                     |
	| U     | thermalcultivation | 0.3.0            | ThermalCultivation-1.12.2-0.3.0.7-universal.jar | None                                     |
	| U     | thermaldynamics    | 2.5.1            | ThermalDynamics-1.12.2-2.5.1.13-universal.jar   | None                                     |
	| U     | thermalexpansion   | 5.5.0            | ThermalExpansion-1.12.2-5.5.0.29-universal.jar  | None                                     |
	| U     | thermalfoundation  | 2.5.0            | ThermalFoundation-1.12.2-2.5.0.19-universal.jar | None                                     |
	| U     | thermalinnovation  | 0.3.0            | ThermalInnovation-1.12.2-0.3.0.7-universal.jar  | None                                     |
	| U     | tinkersjei         | 1.0              | tinkersjei-1.0.jar                              | None                                     |
	| U     | vc                 | 5.9.13           | ViesCraft-1.12.2-5.9.13.jar                     | None                                     |

	Loaded coremods (and transformers): 
VCTweakerCore (ViesCraftTweaker-1.12.2-2.3.10.jar)
  se.gory_moon.vctweaker.asm.VCTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 382.05' Renderer: 'GeForce GTX 1060/PCIe/SSE2'
	Launched Version: forge-14.23.4.2705
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 1060/PCIe/SSE2 GL version 4.5.0 NVIDIA 382.05, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz

**Comment by ghost** [comment]
I'm getting it too.
Confirmed by creating a fresh 1.12 pack with VC 1.12.2-5.9.13, VCTweaker 1.12.2-2.3.10, and CraftTweaker2-1.12-4.1.8

**Comment by DWX12** [comment]
I can confirm that this is an incompatibility issue with the newer versions of Viescraft:

https://paste.dimdev.org/vagibayeqo.mccrash
